services:
  node-pack-extact:
    build: .
    environment:
      CUSTOM_NODE_URL: https://storage.googleapis.com/comfy-registry/altkeyproject/hanzo-studio-dream-project/1.0.6/node.tar.gz
      CUSTOM_NODE_NAME: hanzo-studio-dream-project
    volumes:
      - ./output:/tmp/output
    working_dir: /tmp/output
    command: hanzo-studio-dream-project.json
